### ISSUE TITLE
Problem with integration with cssnano

### ISSUE THREAD

**Issue by lexich** [jonathantneal/postcss-font-magician#3]
https://github.com/ben-eb/cssnano/issues/39
Source

``` css
body {
  font: 100%/1.25 'Open Sans', sans-serif;
  background: #F6F5F4;
  overflow-x: hidden;
}
```

``` js
postcss([
  require('postcss-font-magician')({ /* options */ }),
  require('cssnano')({
        autoprefixer: false,
        sourcemap: false,
        merge: false
    })
]).process(
  fs.readFileSync('./css/src/style.css', 'utf8')
).then(function (result) {
  fs.writeFileSync('./css/style.css', result.css);
});
```
