### ISSUE TITLE
Disable plugin for specific file/fonts

### ISSUE THREAD

**Issue by AdamQuadmon** [jonathantneal/postcss-font-magician#30]
I'm using system font as base font as for this tut https://medium.com/designing-medium/system-shock-6b1dc6d6596f

```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
}
```

Is there a way to not generate the font-face rules for those fonts?
