### ISSUE TITLE
local option return other fonts

### ISSUE THREAD

**Issue by cmnstmntmn** [jonathantneal/postcss-font-magician#34]
i tested with the `font-family: "Alice"` example; works fine

but when i try to use my local font, it fails.

``` js
require('postcss-font-magician')({
  hosted: 'workspace/source/fonts'
}),  
```

``` css
body {
  font-family: "Gotham";
}
```

the result i get is:

``` css
@font-face {
    font-family: monospace;
    font-style: italic;
    font-weight: 400;
    src: local("Menlo Italic"), local(Menlo-Italic), local("Consolas Italic"), local(Consolas-Italic), local("Courier New Italic")
}
@font-face {
    font-family: monospace;
    font-style: italic;
    font-weight: 700;
    src: local("Menlo Bold Italic"), local(Menlo-BoldItalic), local(Monaco), local("Consolas Bold Italic"), local(Consolas-BoldItalic), local("Courier New Bold Italic")
}
@font-face {
    font-family: monospace;
    font-style: normal;
    font-weight: 400;
    src: local("Menlo Regular"), local(Menlo-Regular), local(Monaco), local(Consolas), local("Courier New")
}
@font-face {
    font-family: monospace;
    font-style: normal;
    font-weight: 700;
    src: local("Menlo Bold"), local(Menlo-Bold), local(Monaco), local("Consolas Bold"), local(Consolas-Bold), local("Courier New Bold")
}
@font-face {
    font-family: sans-serif;
    font-style: italic;
    font-weight: 300;
    src: local("Helvetica Neue Light Italic"), local(HelveticaNeue-LightItalic), local("Helvetica Light Oblique"), local(Helvetica-LightOblique)
}
@font-face {
    font-family: sans-serif;
    font-style: italic;
    font-weight: 400;
    src: local("Helvetica Neue Italic"), local(HelveticaNeue-Italic), local("Helvetica Oblique"), local(Helvetica-Oblique)
}
@font-face {
    font-family: sans-serif;
    font-style: italic;
    font-weight: 700;
    src: local("Helvetica Neue Bold Italic"), local(HelveticaNeue-BoldItalic), local("Helvetica Bold Oblique"), local(Helvetica-BoldOblique)
}
@font-face {
    font-family: sans-serif;
    font-style: normal;
    font-weight: 300;
    src: local("Helvetica Neue Light"), local(HelveticaNeue-Light), local("Helvetica Light"), local(Helvetica-Light)
}
@font-face {
    font-family: sans-serif;
    font-style: normal;
    font-weight: 400;
    src: local(HelveticaNeue), local(Helvetica)
}
@font-face {
    font-family: sans-serif;
    font-style: normal;
    font-weight: 700;
    src: local("Helvetica Neue Bold"), local(HelveticaNeue-Bold), local("Helvetica Bold"), local(Helvetica-Bold)
}
```

this is my directory tree

```
\workspace
  source
  css
  fonts
   Gotham\
     Gotham-Black.eot
     ...
```
