### ISSUE TITLE
Font variants properties are swapped

### ISSUE THREAD

**Issue by sms-system** [jonathantneal/postcss-font-magician#45]
In **postcss-font-magician**, when i describe font, in variants section *font-weight* followed after *font-style*

```js
require('postcss-font-magician')({
   custom: {
      'My Special Font': {
         variants: {
            normal: {
               400: {
                  url: {
                     woff2: 'path/to/my-body-font-normal-400.woff2',
                     woff: 'path/to/my-body-font-normal-400.woff'
                  }
               },
               700: {
                  url: {
                     woff2: 'path/to/my-body-font-normal-700.woff2'
                  }
               }
            },
            italic: {
               400: {
                  url: {
                     woff2: 'path/to/my-body-font-italic-400.woff2'
                  }
               }
            }
         }
      }
   }
});
```

But in **directory-fonts-complete** plugin, which is used, when i use `hosted` option *font-style* followed after *font-weight*

```js
{
    "Apple Braille": {
        "variants": {
            "400": {
                "normal": {
                    "local": [
                        "Apple Braille",
                        "AppleBraille"
                    ],
                    "url": {
                        "ttf": "/System/Library/Fonts/Apple Braille.ttf"
                    }
                }
            }
        }
    },
    ...
}
```

So, when i use **postcss-font-magician** with `hosted` option i got this:

```css
@font-face {
    font-family: Font;
    font-style: 400;
    font-weight: 400;
    src: local(Font-Regular), url(path/to/font-regular.woff) format("woff")
}
@font-face {
    font-family: Font;
    font-style: 700;
    font-weight: 400;
    src: local(Font-Bold), url(path/to/font-bold.woff) format("woff")
}
@font-face {
    font-family: Font;
    font-style: 700;
    font-weight: italic;
    src: local(Font-Bold-Italic), url(path/to/font-bold-italic.woff) format("woff")
}
```
