### ISSUE TITLE
@font-face declarations should be placed after @charset rule

### ISSUE THREAD

**Issue by cedx** [jonathantneal/postcss-font-magician#50]
Currently, the plugin ignores `@charset` declarations, and places the `@font-face` declarations at the top of the stylesheet.

Before:

```css
@charset "UTF-8";

body {
  font-family: 'Open Sans', sans-serif;
}
```

After:

```css
@font-face{
  font-family: "Open Sans";
  font-style: normal;
  font-weight: 400;
  src: url(//fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff) format("woff");
}

@charset "UTF-8";

body {
  font-family: 'Open Sans', sans-serif;
}
```

According to the CSS specification, `@charset` declaration should **always** be the first element in the stylesheet and not be preceded by any character (e.g. `@charset` is not a parsed "at-rule", but a raw byte sequence):

- https://drafts.csswg.org/css-syntax-3/#charset-rule
- https://drafts.csswg.org/css-syntax-3/#determine-the-fallback-encoding
